server :
  port : 8080

spring :
  application :
    name : yesim_spring

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/testdb1?characterEncoding=UTF-8&serverTimeZone=UTC
#      username: test1
#      password: full405
      jdbc-url: jdbc:mysql://43.203.24.242:3306/yesim?characterEncoding=UTF-8&serverTimeZone=UTC
      username: portfolio
      password: Java405!@#
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-test-query: SELECT 1

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode : always
  profiles:
    include: aws

image-base-url: 'https://portfolio-yeeun.s3.amazonaws.com/YESIM/image/'
#image-base-url: localhost:8080/
jwt:
  issuer : "yesim_issuer"
  secretKey : "yesim_secretKey"

